version: "3"

services: 

  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - ./app:/app:rw
    env_file: .env #if not .env file in the directory, it will not be loaded. generte .env from .env_example
    command: "flask run -h 0.0.0.0 -p 5000"
    restart: always
    depends_on: 
      - redis

  redis:
    container_name: redis
    image: redis
    ports: 
      - "6379:6379"
    volumes: 
      - ./db:/data